inherit_from:
  - .rubocop_todo.yml

plugins:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2.2
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - 'spec/integration/**/*'
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Style/FrozenStringLiteralComment:
  Enabled: true
  # EnforcedStyle: always
  SafeAutoCorrect: true